# DATA SCIENCE


In [3]:
!pip install numpy

1 CREATE


In [6]:
import numpy as np



In [8]:
data = np.random.rand(2,3,4) #WILL generate random number
zeroes = np.zeros((2,2,2)) #will generaate and replecaiong all value with 0
full = np.full((2,2,2),7) #will generaate and replecaing 0 all value with 7
ones = np.ones((2,2,2)) #replacing the value with 1


In [9]:
data

array([[[0.01736417, 0.19825411, 0.18400822, 0.10466969],
        [0.91577236, 0.35138967, 0.10103157, 0.35691819],
        [0.81651271, 0.00863403, 0.45477708, 0.23132851]],

       [[0.40584107, 0.1830951 , 0.82435868, 0.49512364],
        [0.84479825, 0.86273298, 0.77688951, 0.79298097],
        [0.360056  , 0.36066285, 0.83663756, 0.98446731]]])

In [10]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [14]:
arr = np.array([[1,2,3,4],[6,7,8,8]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
#READ

In [17]:
#ATTRIBUTES
shape = data.shape
size = data.size
types = data.dtype

In [18]:
shape #will give youbacces what the value before
size
types

dtype('float64')

In [20]:
shape

(2, 3, 4)

In [23]:
#SLICING
arr = data[0]
slicer = data[0:2]
reverse = data[-1]
singlevel= data[0][0][0]

In [24]:
arr   #array([[0.01736417, 0.19825411, 0.18400822, 0.10466969],
       [0.91577236, 0.35138967, 0.10103157, 0.35691819],
       [0.81651271, 0.00863403, 0.45477708, 0.23132851]])

array([[0.01736417, 0.19825411, 0.18400822, 0.10466969],
       [0.91577236, 0.35138967, 0.10103157, 0.35691819],
       [0.81651271, 0.00863403, 0.45477708, 0.23132851]])

In [27]:
slicer #array([[[0.01736417, 0.19825411, 0.18400822, 0.10466969],
        [0.91577236, 0.35138967, 0.10103157, 0.35691819],
        [0.81651271, 0.00863403, 0.45477708, 0.23132851]],
       [[0.40584107, 0.1830951 , 0.82435868, 0.49512364],
        [0.84479825, 0.86273298, 0.77688951, 0.79298097],
        [0.360056  , 0.36066285, 0.83663756, 0.98446731]]])

IndentationError: unexpected indent (<ipython-input-27-d245063cdcc3>, line 2)

In [28]:
singlevel #0.017364168159434756

0.017364168159434756

In [30]:
reverse #grabbing the last arrayarray([[0.40584107, 0.1830951 , 0.82435868, 0.49512364],
       [0.84479825, 0.86273298, 0.77688951, 0.79298097],
       [0.360056  , 0.36066285, 0.83663756, 0.98446731]])

IndentationError: unexpected indent (<ipython-input-30-b2c2c6806e6a>, line 2)

In [33]:
#Update
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [34]:
list1


array([0.55427793, 0.12224314, 0.23759892, 0.07389245, 0.24869715,
       0.34594973, 0.82410693, 0.59961645, 0.94981257, 0.56199585])

In [36]:
#BASIC MATH
add = np.add(list1,list2)
sub = np.subtract(list1,list2)
div = np.divide(list1,list2)
mult = np.multiply(list1,list2)
dot = np.dot(list1,list2)
                  

In [37]:
add

array([1.37195688, 0.61667629, 0.94354355, 0.79426077, 0.50906364,
       0.90304662, 0.90200209, 1.11862543, 1.20812824, 0.98937101])

In [38]:
sub

array([-0.26340102, -0.37219002, -0.46834571, -0.64647588, -0.01166934,
       -0.21114715,  0.74621178,  0.08060748,  0.69149689,  0.13462069])

In [39]:
div

array([ 0.67786744,  0.24723896,  0.33656877,  0.10257592,  0.9551811 ,
        0.62098666, 10.57969409,  1.15531037,  3.67694512,  1.31499418])

In [40]:
dot


1.8530386378458357

In [43]:
#STATISTIC FUNCTIONS SAPLAMM
sqrt = np.sqrt(25) #SQUART
ab = np.abs(-1)#convert to absolute value
power = np.power(2,7) # calculate the power ,2^7
log = np.log(25)
exp = np.exp([2,3]) # create expponensial and calculate exponensial
mins = np.min(list1) #MINIMUM
maxs = np.max(list2) #MAKSIMUM

In [44]:
maxs


0.8176789464446764

In [45]:
data[0][0][0]= 700


In [46]:
data

array([[[7.00000000e+02, 1.98254109e-01, 1.84008221e-01, 1.04669693e-01],
        [9.15772362e-01, 3.51389666e-01, 1.01031568e-01, 3.56918189e-01],
        [8.16512711e-01, 8.63402588e-03, 4.54777082e-01, 2.31328506e-01]],

       [[4.05841066e-01, 1.83095095e-01, 8.24358676e-01, 4.95123641e-01],
        [8.44798246e-01, 8.62732983e-01, 7.76889514e-01, 7.92980974e-01],
        [3.60055996e-01, 3.60662854e-01, 8.36637562e-01, 9.84467308e-01]]])

In [47]:
data.sort() #SORTING

In [48]:
data

array([[[1.04669693e-01, 1.84008221e-01, 1.98254109e-01, 7.00000000e+02],
        [1.01031568e-01, 3.51389666e-01, 3.56918189e-01, 9.15772362e-01],
        [8.63402588e-03, 2.31328506e-01, 4.54777082e-01, 8.16512711e-01]],

       [[1.83095095e-01, 4.05841066e-01, 4.95123641e-01, 8.24358676e-01],
        [7.76889514e-01, 7.92980974e-01, 8.44798246e-01, 8.62732983e-01],
        [3.60055996e-01, 3.60662854e-01, 8.36637562e-01, 9.84467308e-01]]])

In [49]:
#RESHAPE ARRAY 
print(data.shape)

(2, 3, 4)


In [51]:
data.reshape((2,2,-1))
data.shape

(2, 3, 4)

In [52]:
zeroes = np.zeros((8))

In [53]:
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
zeroes = np.append(zeroes,[3,4]) #push array to the las

In [56]:
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [62]:
zeroes=np.insert(zeroes,2,1)
#param(initial value,the position por place the value, include vthe value that want to insert)

In [63]:
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


# DELETE

In [64]:
data

array([[[1.04669693e-01, 1.84008221e-01, 1.98254109e-01, 7.00000000e+02],
        [1.01031568e-01, 3.51389666e-01, 3.56918189e-01, 9.15772362e-01],
        [8.63402588e-03, 2.31328506e-01, 4.54777082e-01, 8.16512711e-01]],

       [[1.83095095e-01, 4.05841066e-01, 4.95123641e-01, 8.24358676e-01],
        [7.76889514e-01, 7.92980974e-01, 8.44798246e-01, 8.62732983e-01],
        [3.60055996e-01, 3.60662854e-01, 8.36637562e-01, 9.84467308e-01]]])

In [70]:
delete_value = np.delete(data,0,axis=1) # (data,whih level,if we spesific axis,it mean its arrow)

In [69]:
delete_value

array([[[0.10103157, 0.35138967, 0.35691819, 0.91577236],
        [0.00863403, 0.23132851, 0.45477708, 0.81651271]],

       [[0.77688951, 0.79298097, 0.84479825, 0.86273298],
        [0.360056  , 0.36066285, 0.83663756, 0.98446731]]])

In [73]:
# test = np.load('dataScienceBasic',data)